CREATE TABLE "STD_OBJECTS" 
   (  "GROUP_NAME" VARCHAR2(100), 
  "OBJECT_NAME" VARCHAR2(100), 
  "CREATED_BY" VARCHAR2(100), 
  "CREATION_DATE" DATE, 
  "LAST_UPDATED_BY" VARCHAR2(100), 
  "LAST_UPDATE_DATE" DATE, 
  "OBJ_TYPE" VARCHAR2(100),
  "OBJ" CLOB,
  "APP_SESSION" VARCHAR2(100)
   );

