ALTER TABLE "STD_OBJECTS" ADD CONSTRAINT "STD_OBJECTS_CHK8" CHECK ("OBJ" IS JSON) ENABLE;

ALTER TABLE "STD_OBJECTS" ADD CONSTRAINT "STD_OBJECTS_PK" PRIMARY KEY ("GROUP_NAME", "OBJECT_NAME") ENABLE;

