ALTER TABLE "STD_OBJECTS" ADD CONSTRAINT "STD_OBJECTS_CHK1" CHECK ("CREATED_BY" IS NOT NULL) ENABLE;

ALTER TABLE "STD_OBJECTS" ADD CONSTRAINT "STD_OBJECTS_CHK2" CHECK ("CREATION_DATE" IS NOT NULL) ENABLE;

ALTER TABLE "STD_OBJECTS" ADD CONSTRAINT "STD_OBJECTS_CHK3" CHECK ("LAST_UPDATED_BY" IS NOT NULL) ENABLE;

ALTER TABLE "STD_OBJECTS" ADD CONSTRAINT "STD_OBJECTS_CHK4" CHECK ("LAST_UPDATE_DATE" IS NOT NULL) ENABLE;

ALTER TABLE "STD_OBJECTS" ADD CONSTRAINT "STD_OBJECTS_CHK5" CHECK ("OBJ_TYPE" IS NOT NULL) ENABLE;

ALTER TABLE "STD_OBJECTS" ADD CONSTRAINT "STD_OBJECTS_CHK6" CHECK ("OBJ" IS NOT NULL) ENABLE;

ALTER TABLE "STD_OBJECTS" ADD CONSTRAINT "STD_OBJECTS_CHK7" CHECK ("APP_SESSION" IS NOT NULL) ENABLE;

ALTER TABLE "STD_OBJECTS" ADD CONSTRAINT "STD_OBJECTS_CHK8" CHECK ("OBJ" IS JSON) ENABLE;

ALTER TABLE "STD_OBJECTS" ADD CONSTRAINT "STD_OBJECTS_PK" PRIMARY KEY ("GROUP_NAME", "OBJECT_NAME") ENABLE;

