whenever oserror exit failure
whenever sqlerror exit failure
set define off sqlblanklines on
ALTER SESSION SET PLSQL_WARNINGS = 'ENABLE:ALL';

rem prompt @@R__0001.PUBLIC.SYNONYM.DBUG_TRIGGER.sql
rem @@R__0001.PUBLIC.SYNONYM.DBUG_TRIGGER.sql
rem prompt @@R__0002.PUBLIC.SYNONYM.DBUG.sql
rem @@R__0002.PUBLIC.SYNONYM.DBUG.sql
prompt @@0003.TYPE_SPEC.STD_OBJECT.sql
@@0003.TYPE_SPEC.STD_OBJECT.sql
show errors TYPE "STD_OBJECT"
prompt @@0004.TYPE_SPEC.DBUG_LOG4PLSQL_OBJ_T.sql
@@0004.TYPE_SPEC.DBUG_LOG4PLSQL_OBJ_T.sql
show errors TYPE "DBUG_LOG4PLSQL_OBJ_T"
prompt @@0005.TYPE_SPEC.DBUG_CALL_OBJ_T.sql
@@0005.TYPE_SPEC.DBUG_CALL_OBJ_T.sql
show errors TYPE "DBUG_CALL_OBJ_T"
prompt @@0006.TYPE_SPEC.DBUG_CALL_TAB_T.sql
@@0006.TYPE_SPEC.DBUG_CALL_TAB_T.sql
show errors TYPE "DBUG_CALL_TAB_T"
prompt @@0007.TYPE_SPEC.DBUG_OBJ_T.sql
@@0007.TYPE_SPEC.DBUG_OBJ_T.sql
show errors TYPE "DBUG_OBJ_T"
prompt @@R__0008.TYPE_BODY.STD_OBJECT.sql
@@R__0008.TYPE_BODY.STD_OBJECT.sql
show errors TYPE BODY "STD_OBJECT"
prompt @@0009.TABLE.STD_OBJECTS.sql
@@0009.TABLE.STD_OBJECTS.sql
prompt @@R__0010.TYPE_BODY.DBUG_LOG4PLSQL_OBJ_T.sql
@@R__0010.TYPE_BODY.DBUG_LOG4PLSQL_OBJ_T.sql
show errors TYPE BODY "DBUG_LOG4PLSQL_OBJ_T"
prompt @@R__0011.PACKAGE_SPEC.DBUG.sql
@@R__0011.PACKAGE_SPEC.DBUG.sql
show errors PACKAGE "DBUG"
prompt @@R__0012.TYPE_BODY.DBUG_OBJ_T.sql
@@R__0012.TYPE_BODY.DBUG_OBJ_T.sql
show errors TYPE BODY "DBUG_OBJ_T"
prompt @@R__0013.PACKAGE_SPEC.DBUG_TRIGGER.sql
@@R__0013.PACKAGE_SPEC.DBUG_TRIGGER.sql
show errors PACKAGE "DBUG_TRIGGER"
prompt @@R__0014.PACKAGE_SPEC.DBUG_PROFILER.sql
@@R__0014.PACKAGE_SPEC.DBUG_PROFILER.sql
show errors PACKAGE "DBUG_PROFILER"
prompt @@R__0015.PACKAGE_SPEC.DBUG_LOG4PLSQL.sql
@@R__0015.PACKAGE_SPEC.DBUG_LOG4PLSQL.sql
show errors PACKAGE "DBUG_LOG4PLSQL"
prompt @@R__0016.PACKAGE_SPEC.DBUG_DBMS_OUTPUT.sql
@@R__0016.PACKAGE_SPEC.DBUG_DBMS_OUTPUT.sql
show errors PACKAGE "DBUG_DBMS_OUTPUT"
prompt @@R__0017.PACKAGE_SPEC.DBUG_DBMS_APPLICATION_INFO.sql
@@R__0017.PACKAGE_SPEC.DBUG_DBMS_APPLICATION_INFO.sql
show errors PACKAGE "DBUG_DBMS_APPLICATION_INFO"
prompt @@R__0018.PACKAGE_BODY.DBUG_TRIGGER.sql
@@R__0018.PACKAGE_BODY.DBUG_TRIGGER.sql
show errors PACKAGE BODY "DBUG_TRIGGER"
prompt @@R__0019.PACKAGE_BODY.DBUG_PROFILER.sql
@@R__0019.PACKAGE_BODY.DBUG_PROFILER.sql
show errors PACKAGE BODY "DBUG_PROFILER"
prompt @@R__0020.PACKAGE_BODY.DBUG_LOG4PLSQL.sql
@@R__0020.PACKAGE_BODY.DBUG_LOG4PLSQL.sql
show errors PACKAGE BODY "DBUG_LOG4PLSQL"
prompt @@R__0021.PACKAGE_BODY.DBUG_DBMS_OUTPUT.sql
@@R__0021.PACKAGE_BODY.DBUG_DBMS_OUTPUT.sql
show errors PACKAGE BODY "DBUG_DBMS_OUTPUT"
prompt @@R__0022.PACKAGE_BODY.DBUG_DBMS_APPLICATION_INFO.sql
@@R__0022.PACKAGE_BODY.DBUG_DBMS_APPLICATION_INFO.sql
show errors PACKAGE BODY "DBUG_DBMS_APPLICATION_INFO"
prompt @@R__0023.PACKAGE_BODY.DBUG.sql
@@R__0023.PACKAGE_BODY.DBUG.sql
show errors PACKAGE BODY "DBUG"
prompt @@0024.INDEX.STD_OBJECTS.sql
@@0024.INDEX.STD_OBJECTS.sql
prompt @@0025.CONSTRAINT.STD_OBJECTS.sql
@@0025.CONSTRAINT.STD_OBJECTS.sql
prompt @@R__0026.OBJECT_GRANT.DBUG.sql
@@R__0026.OBJECT_GRANT.DBUG.sql
