ALTER TABLE "STD_OBJECTS" MODIFY "GROUP_NAME" VARCHAR2(512 CHAR);

ALTER TABLE "STD_OBJECTS" MODIFY "APP_SESSION" VARCHAR2(128 CHAR);

ALTER TABLE "STD_OBJECTS" DROP CONSTRAINT "STD_OBJECTS_CHK8";

ALTER TABLE "STD_OBJECTS" RENAME COLUMN "APP_SESSION" TO "DB_SESSION";

ALTER TABLE "STD_OBJECTS" ADD CONSTRAINT "STD_OBJECTS_CHK8" CHECK ("DB_SESSION" IS NOT NULL) ENABLE;




